package Dashboard;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JFrame;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import savic.application.form.LoginForm;
import savic.application.form.MainForm;
import savic.application.form.FormDisplayReports;
import savic.menu.xdd;
import raven.toast.Notifications;
import savic_application.Application;
import savic.mainCashierJFrame.NewJFrameCashier;

/**
 *
 * @author ABDURAHMAN
 */
public class LogoutPAGE extends javax.swing.JFrame {

    /**
     * Creates new form LogoutPAGE
     */
   //private JFrame jframe;
   //private static Application app;T
   //private MainForm mainForm;

    public LogoutPAGE() {
        
        
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("raven.theme");
        FlatMacLightLaf.setup();
        FlatLaf.updateUI();
        initComponents();
        
        
       
        
        
        
        this.setResizable(false);
        this.setVisible(true);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
         // Set the look and feel to default light mode
        try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLightLaf");
        }
    }
    
//     public static void setSelectedMenu(int index, int subIndex) {
//        app.mainForm.setSelectedMenu(index, subIndex);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Cashier_btn = new javax.swing.JButton();
        Manager_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(203, 195, 227));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lobby");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        Cashier_btn.setBackground(new java.awt.Color(0, 102, 0));
        Cashier_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cashier_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesLogin/cashier _logoutPage.png"))); // NOI18N
        Cashier_btn.setText("      Cashier");
        Cashier_btn.setFocusPainted(false);
        Cashier_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cashier_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Cashier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cashier_btnActionPerformed(evt);
            }
        });

        Manager_btn.setBackground(new java.awt.Color(36, 103, 155));
        Manager_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Manager_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesLogin/Manager_logoutPage.png"))); // NOI18N
        Manager_btn.setText("      Manager");
        Manager_btn.setFocusPainted(false);
        Manager_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Manager_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Manager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_btnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Restaurant Copyright");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesLogin/logoutPage_headerImage.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cashier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Manager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Manager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cashier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Manager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Manager_btn) {
            // Move to the Application class
          
//            app = new Application();
//            app.setVisible(true);
            
            ManagerLogin managerLogin = new ManagerLogin();
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_Manager_btnActionPerformed

//    public static void showForm(Component component) {
//        component.applyComponentOrientation(app.getComponentOrientation());
//        app.mainForm.showForm(component);
//    }
    
    private void Cashier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cashier_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Cashier_btn) {
            // Move to the NewJFrameCashier class
//            NewJFrameCashier cashier = new NewJFrameCashier();
//            cashier.setVisible(true);
    
            
            FlatLightLaf.setup();
            FlatLightLaf.updateUI();
            CashierLogin cashierLogin = new CashierLogin();
            this.dispose();
        }
    }//GEN-LAST:event_Cashier_btnActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {

        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> {
            LogoutPAGE app = new LogoutPAGE();
            app.setVisible(true);
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cashier_btn;
    private javax.swing.JButton Manager_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
