/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package savic.application.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static restaurant.Generate_Report.currentDate;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.sql.Timestamp;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.time.LocalDate;
import java.text.SimpleDateFormat;

/**
 *
 * @author ABDURAHMAN
 */
public class FormGenerateReport extends javax.swing.JPanel {

    /**
     * Creates new form FormGenerateReport
     */
    private static final String URL = "jdbc:mysql://localhost:3306/restaurant";
    private static final String USER = "root";
    private static final String PASSWORD = "0503838Aqq"; 
    public static Date currentDate = new Date();
    
    public FormGenerateReport() {
        initComponents();
        
          //generate report
           jButton7.addActionListener(new ActionListener() {
             public void actionPerformed(ActionEvent e) {
              
              
              jTextField5.setText(leastordered());        
              jTextField3.setText(mostordered());     
              jTextField4.setText(String.valueOf(getsalesid() + 1));    
              jTextField2.setText(new SimpleDateFormat("yyyy-MM-dd").format(currentDate));  
              jTextField1.setText(String.valueOf(totalorders()));   
              GenerateReport();
              
            
             }
           });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(36, 103, 155));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setText("Generate a report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(456, 456, 456))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
        );

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel9.setText("Date");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setText("Total Orders");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setText("Most Ordered");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setText("Least Ordered");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setText("ID");

        jButton7.setBackground(new java.awt.Color(36, 103, 155));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton7.setText("Generate");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(502, 502, 502))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

     static void GenerateReport(){
    
    
      if(Exists(totalorders() , currentDate)){ 
         JOptionPane.showMessageDialog(null, "Report already exists", "Error", JOptionPane.ERROR_MESSAGE); 
         return;
      }
    
      else{
          insertodatabase();
         JOptionPane.showMessageDialog(null, "Report has been saved!", "Report Saved", JOptionPane.INFORMATION_MESSAGE); 
      }
     }

    
    
     
    
    
    static void insertodatabase(){
        
        
        Date reportDate = new Date(System.currentTimeMillis());
        String sql = "INSERT INTO sales_report (Sales_Id, MO_Item, LO_Item, Total_Orders, Report_Date, E_Id) VALUES (?, ?, ?, ?, ?, ?)";
        
        try (
            Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
        ) {
            preparedStatement.setInt(1, getsalesid() + 1);
            preparedStatement.setString(2, leastordered());
            preparedStatement.setString(3, mostordered());
            preparedStatement.setInt(4, totalorders());
            preparedStatement.setDate(5,  new java.sql.Date(reportDate.getTime()));
            preparedStatement.setInt(6, 1000);
            
            int rowsAffected = preparedStatement.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("Record inserted successfully.");
            } else {
                System.out.println("Failed to insert record.");
            }
        } catch (SQLException e) {
            
            System.out.println("error");
            e.printStackTrace();
        }  
        
        
        
    }
    
    
    
    
    
    
    static int totalorders(){
        
     try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            
        }
        
        // SQL query to get row count
        String sql = "SELECT COUNT(*) AS row_count FROM Invoice " +
             "WHERE Order_Date = (SELECT MAX(Order_Date) FROM Invoice)";
        
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            
            if (resultSet.next()) {
                int rowCount = resultSet.getInt("row_count");
                return rowCount;
                
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }   
        return 0;
   
    }
    
    
    static String mostordered(){
        
        int itemId = 0;
                String sql = "SELECT t.Item_Id\n" +
                             "FROM take t\n" +
                             "JOIN (\n" +
                             "    SELECT Order_ID\n" +
                             "    FROM invoice\n" +
                             "    WHERE Order_Date = (\n" +
                             "        SELECT Order_Date\n" +
                             "        FROM invoice\n" +
                             "        ORDER BY Order_ID DESC\n" +
                             "        LIMIT 1\n" +
                             "    )\n" +
                             ") i ON t.Invoice_ID = i.Order_ID\n" +
                             "ORDER BY t.Quantity DESC\n" +
                             "LIMIT 1;";

        try (
            Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql)
        ) {
            if (resultSet.next()) {
                 itemId = resultSet.getInt("Item_Id");
            } 
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
            //Name of food
            String sql2 = "SELECT Name_Of_Food " +
                         "FROM menu " +
                         "WHERE Item_Id = ?";

            try (
                Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
                PreparedStatement statement = connection.prepareStatement(sql2)
            ) {
                statement.setInt(1, itemId);

                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        String nameOfFood = resultSet.getString("Name_Of_Food");
                        return nameOfFood;
                    } 
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        return null;
   
    }
    
    static String leastordered(){
        
        int itemId = -1;
        
       String sql1 = "SELECT m.Item_Id\n" +
                      "FROM menu m\n" +
                      "LEFT JOIN (\n" +
                      "    SELECT t.Item_Id\n" +
                      "    FROM take t\n" +
                      "    JOIN (\n" +
                      "        SELECT Order_ID\n" +
                      "        FROM invoice\n" +
                      "        WHERE Order_Date = (\n" +
                      "            SELECT Order_Date\n" +
                      "            FROM invoice\n" +
                      "            ORDER BY Order_ID DESC\n" +
                      "            LIMIT 1\n" +
                      "        )\n" +
                      "    ) i ON t.Invoice_ID = i.Order_ID\n" +
                      ") t ON m.Item_Id = t.Item_Id\n" +
                      "WHERE t.Item_Id IS NULL\n" +
                      "ORDER BY m.Item_Id\n" +
                      "LIMIT 1;";

        // SQL query to fetch least ordered item_id from take table
        String sql2 = "SELECT t.Item_Id\n" +
                      "FROM take t\n" +
                      "JOIN (\n" +
                      "    SELECT Order_ID\n" +
                      "    FROM invoice\n" +
                      "    WHERE Order_Date = (\n" +
                      "        SELECT Order_Date\n" +
                      "        FROM invoice\n" +
                      "        ORDER BY Order_ID DESC\n" +
                      "        LIMIT 1\n" +
                      "    )\n" +
                      ") i ON t.Invoice_ID = i.Order_ID\n" +
                      "ORDER BY t.Quantity ASC\n" +
                      "LIMIT 1;";

        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement statement = connection.createStatement()) {
            // Attempt to execute the first query
            ResultSet resultSet1 = statement.executeQuery(sql1);
            if (resultSet1.next()) {
                itemId = resultSet1.getInt("Item_Id");
            } else {
                // If no item_id found, execute the second query
                ResultSet resultSet2 = statement.executeQuery(sql2);
                if (resultSet2.next()) {
                    itemId = resultSet2.getInt("Item_Id");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        // Print the result
        if (itemId != -1) {
            System.out.println("Item_ID found: " + itemId);
        } else {
            System.out.println("No Item_ID found.");
        }
        
            //Name of food
            String sql3 = "SELECT Name_Of_Food " +
                         "FROM menu " +
                         "WHERE Item_Id = ?";

            try (
                Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
                PreparedStatement statement = connection.prepareStatement(sql3)
            ) {
                statement.setInt(1, itemId);

                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        String nameOfFood = resultSet.getString("Name_Of_Food");
                        return nameOfFood;
                    } 
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        return null; 
        
    }
    
    
    
    
    static boolean Exists(int total, Date currentDate){
        
    String sql = "SELECT Sales_Id, MO_Item, LO_Item, Total_Orders, Report_Date, E_Id FROM sales_report ORDER BY Sales_Id DESC LIMIT 1";
        
        int totalOrders = 0;
        Date reportDate = null;
        
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            
            if (resultSet.next()) {
                totalOrders = resultSet.getInt("Total_Orders");
                reportDate = resultSet.getDate("Report_Date");
            }
            
            if(new SimpleDateFormat("yyyy-MM-dd").format(currentDate).equals(new SimpleDateFormat("yyyy-MM-dd").format(reportDate)) && total==totalOrders){
              
               return true;
                
            }
            // Printing retrieved data
            System.out.println("Total Orders: " + totalOrders);
            System.out.println("Report Date: " + reportDate);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }   
        
        
        return false;
    
    }
    

    
    
    static int getsalesid(){
       String sql = "SELECT MAX(Sales_Id) AS LastAddedId FROM sales_report";
        int lastAddedId = 0;
        try (
            Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);
        ) {
            if (resultSet.next()) {
                 lastAddedId = resultSet.getInt("LastAddedId");
            } 
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return lastAddedId;
        
    }
    
    static Date datetostring(Date datestring){
       String pattern = "yyyy-MM-dd";

        SimpleDateFormat sdf = new SimpleDateFormat(pattern);

        String dateString = sdf.format(datestring);
        
        return datestring;
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
