/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABDURAHMAN
 */
public class FormCustomerViews extends javax.swing.JPanel {

    /**
     * Creates new form FormCustomerViews
     */
    public FormCustomerViews() {
        initComponents();
        Connect();
        update_table();
    }

    
Connection con;
    PreparedStatement pst;
    
    public void Connect()
    {
      
      
      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_project","root","0503838Aqq");   
            System.out.println("w");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormCustomerViews.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormCustomerViews.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }    
      
      
      public void update_table()
    {
        
        try {
            int CC;
            
            
            pst = con.prepareStatement("SELECT * FROM customer;");
            ResultSet Rs = pst.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            while(Rs.next())
            {
                Vector v2 = new Vector();
                
                for(int i=1; i<=CC ; i++)
                {
                    v2.add(Rs.getString("C_PhoneNo"));
                    v2.add(Rs.getString("C_Fname"));
                    v2.add(Rs.getString("C_Lname"));
                    v2.add(Rs.getString("Total_Point"));                    
                    v2.add(Rs.getString("Gender"));
                    v2.add(Rs.getString("Invoice_Id"));

                }
                model.addRow(v2);
            }

        } catch (Exception e) {
            
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Most_Order = new javax.swing.JButton();
        Least_Order = new javax.swing.JButton();
        txt_Search3 = new javax.swing.JTextField();

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C_PhoneNo", "C_Fname", "C_Lname", "Total_Point", "Gender", "Invoice_ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setText("View of Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(456, 456, 456))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
        );

        Most_Order.setBackground(new java.awt.Color(102, 102, 255));
        Most_Order.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        Most_Order.setText("Most Customers Point");
        Most_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Most_OrderActionPerformed(evt);
            }
        });

        Least_Order.setBackground(new java.awt.Color(102, 102, 255));
        Least_Order.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        Least_Order.setText("Least Customers Point");
        Least_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Least_OrderActionPerformed(evt);
            }
        });

        txt_Search3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Search3.setText("Search an employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Most_Order)
                        .addGap(45, 45, 45)
                        .addComponent(Least_Order)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Search3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(240, 240, 240))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txt_Search3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Most_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Least_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Most_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Most_OrderActionPerformed
        // TODO add your handling code here:
        try
        {
            pst = con.prepareStatement("SELECT * FROM customer ORDER BY Total_Point DESC");

            // Execute the prepared statement and store the results in a ResultSet
            ResultSet rs = pst.executeQuery();

            // Create a DefaultTableModel with one column for IDs
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("C_PhoneNo");
            model.addColumn("C_Fname");
            model.addColumn("C_Lname");
            model.addColumn("Total_Point");
            model.addColumn("Gender");
            model.addColumn("Invoice_Id");

            // Process the results and add each ID to the model
            while (rs.next())
            {
                String phone = rs.getString("C_PhoneNo");
                String fname = rs.getString("C_Fname");
                String lname = rs.getString("C_Lname");
                int totalPoint = rs.getInt("Total_Point");
                String gender = rs.getString("Gender");
                int invoiceId = rs.getInt("Invoice_Id");

                model.addRow(new Object[]{phone, fname, lname, totalPoint, gender, invoiceId});
            }

            // Set the model to the JTable to replace the existing data
            jTable1.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(FormCustomerViews.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Most_OrderActionPerformed

    private void Least_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Least_OrderActionPerformed
        // TODO add your handling code here:
        try
        {
            pst = con.prepareStatement("SELECT * FROM customer ORDER BY Total_Point ASC");

            // Execute the prepared statement and store the results in a ResultSet
            ResultSet rs = pst.executeQuery();

            // Create a DefaultTableModel with one column for IDs
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("C_PhoneNo");
            model.addColumn("C_Fname");
            model.addColumn("C_Lname");
            model.addColumn("Total_Point");
            model.addColumn("Gender");
            model.addColumn("Invoice_Id");

            // Process the results and add each ID to the model
            while (rs.next())
            {
                String phone = rs.getString("C_PhoneNo");
                String fname = rs.getString("C_Fname");
                String lname = rs.getString("C_Lname");
                int totalPoint = rs.getInt("Total_Point");
                String gender = rs.getString("Gender");
                int invoiceId = rs.getInt("Invoice_Id");

                model.addRow(new Object[]{phone, fname, lname, totalPoint, gender, invoiceId});
            }

            // Set the model to the JTable to replace the existing data
            jTable1.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(FormCustomerViews.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Least_OrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Least_Order;
    private javax.swing.JButton Most_Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Search3;
    // End of variables declaration//GEN-END:variables
}
